CREATE TABLE TBL_PRODUCT_01 (
    PCODE VARCHAR2(10) NOT NULL,
    NAME VARCHAR2(20),
    COST NUMBER(10),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PCODE)
);

CREATE TABLE TBL_SHOP_01 (
    SCODE VARCHAR2(10) NOT NULL,
    SNAME VARCHAR2(20),
    CONSTRAINT PK_SHOP PRIMARY KEY (SCODE)
);

CREATE TABLE TBL_SALELIST_01 (
    SALENO NUMBER(10) NOT NULL,
    PCODE VARCHAR2(10) NOT NULL,
    SALEDATE DATE,
    SCODE VARCHAR2(10) NOT NULL,
    AMOUNT NUMBER(10),
    CONSTRAINT PK_SALELIST PRIMARY KEY (SALENO)
);